import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

// 💡 Fontok helyben, offline buildhez – relatív útvonal a src/app -> public/fonts mappához
// (nem a next/font/google-t használjuk, mert a szerveren nincs
// internet-elérés a build/futás közben, a Google-ös betűtípus
// letöltése emiatt elhasalna).
export const geist = localFont({
  src: "../../public/fonts/Geist-Regular.woff2",
  variable: "--font-geist",
  weight: "400",
  style: "normal",
});

export const geistMono = localFont({
  src: "../../public/fonts/GeistMono-Regular.woff2",
  variable: "--font-geist-mono",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
